// Regenerates web/traces.js from samples/*.json by running the real parser
// with --trace. The output is a plain <script> so web/index.html works when
// opened straight from disk (no fetch, no server needed).
//
//   node scripts/gen-traces.mjs [path/to/jsonparser]
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const candidates = [
  process.argv[2],
  join(root, "build", "jsonparser.exe"),
  join(root, "build", "jsonparser"),
  join(root, "build", "Release", "jsonparser.exe"),
].filter(Boolean);
const bin = candidates.find((p) => existsSync(p));
if (!bin) {
  console.error("jsonparser binary not found; build it first (see README)");
  process.exit(2);
}

const samplesDir = join(root, "samples");
const traces = [];
for (const file of readdirSync(samplesDir).filter((f) => f.endsWith(".json")).sort()) {
  let out;
  try {
    out = execFileSync(bin, ["--trace", join(samplesDir, file)], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  } catch (e) {
    if (e.status !== 1) throw e; // 1 = parse error, trace is still on stdout
    out = e.stdout;
  }
  const trace = JSON.parse(out);
  trace.name = file.replace(/\.json$/, "");
  traces.push(trace);
  console.log(`${file}: ${trace.events.length} events, ${trace.ok ? "ok" : "error at " + trace.error.line + ":" + trace.error.col}`);
}

const header = "// Generated by scripts/gen-traces.mjs from samples/*.json. Do not edit.\n";
writeFileSync(join(root, "web", "traces.js"), header + "window.TRACES = " + JSON.stringify(traces) + ";\n");
console.log(`wrote web/traces.js (${traces.length} traces)`);
